import { makeStyles } from '@mui/styles';

export const useStyles = makeStyles({
  wrapper: {
    marginTop: '100px',
    padding: '20px',
  },
  techCarouselWrapper: {
    display: 'flex',
    gap: 8,
    overflow: 'hidden',
    position: 'relative',
    padding: '0 40px',
    marginBottom: 30,
  },
  carouselNavLeft: {
    position: 'absolute',
    left: 0,
    width: '30px',
    height: '30px',
    top: '50%',
    color: 'white',
    transform: 'translateY(-50%)',
    zIndex: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    '&:hover': {
      backgroundColor: 'rgba(255,255,255,0.2)',
    },
  },
  carouselNavRight: {
    position: 'absolute',
    right: 0,
    top: '50%',
    width: '30px',
    height: '30px',
    color: 'white',
    transform: 'translateY(-50%)',
    zIndex: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    '&:hover': {
      backgroundColor: 'rgba(255,255,255,0.2)',
    },
  },
  techButton: {
    whiteSpace: 'nowrap',
    minWidth: 'auto',
    width: 200,
    flexShrink: 0,
    borderRadius: '20px',
    fontSize: '13px',
    textTransform: 'none',
  },
  baseEmpty: {
    width: '100%',
    height: '80vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  masonryGrid: {
    display: 'flex',
    marginLeft: '-38px',
    width: '100%',
    height: '80vh',
    overflowY: 'scroll',
  },
  masonryColumn: {
    paddingLeft: '16px',
    backgroundClip: 'padding-box',
    '& > div': {
      marginBottom: '16px',
    },
  },
  postCard: {
    background: 'rgba(90,99,106,0.30)',
    borderRadius: '10px',
    padding: '15px',
    marginBottom: '16px',
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: '50%',
  },
  mediaContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  postImage: {
    width: '100%',
    objectFit: 'cover',
    borderRadius: '8px',
    cursor: 'pointer',
  },
  tag: {
    color: 'white',
    backgroundColor: 'rgba(90,99,106,0.40)',
    borderRadius: '20px',
    padding: '4px 10px',
    fontSize: '13px',
  },
  loadingWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '90vh',
    padding: '20px',
    marginLeft: '-40px',
    background: 'transparent',
    overflow: 'hidden',
  },
  skeletonGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '20px',
    width: '100%',
    justifyContent: 'center',
  },
  skeletonBox: {
    width: '300px',
    borderRadius: '10px',
    background: 'rgba(255,255,255,0.05)',
    padding: '10px',
  },
});
